### ISSUE TITLE
Check the validity of the version of the plugins to be installed

### ISSUE THREAD

**Issue by vicente23** [qgis-deployment/qgis-deployment-toolbelt-cli#115]
Check the validity of the version of the plugins to be installed and inform the user

**Comment by Guts** [comment]
We propose adding an option to the [Profiles Synchronizer](https://qgis-deployment.github.io/qgis-deployment-toolbelt-cli/jobs/profiles_synchronizer.html) job to verify that the QGIS version detected on the machine (via the [QGIS Installation Finder](https://qgis-deployment.github.io/qgis-deployment-toolbelt-cli/jobs/qgis_installation_finder.html) falls within the version range declared in the `profile.json` files. This check should also apply to all plugins listed in the profiles.

The configuration could then look like this:

```yaml
- name: Synchronize installed profiles from downloaded ones
  uses: qprofiles-synchronizer
  with:
    check_qgis_version_compatibility_profiles: true
    check_qgis_version_compatibility_plugins: true
    sync_mode: only_new_version
```
